display_name: Xlclash
package_name: xlclash
maintainer:
  name: chen08209
  email: chen08209@gmail.com

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/icon.png

dependencies:
  - libayatana-appindicator3-dev
  - libkeybinder-3.0-dev
  - libsecret-1-0

keywords:
  - Xlclash
  - Clash
  - ClashMeta
  - Proxy

generic_name: Xlclash

categories:
  - Network

startup_notify: true
